#!/bin/bash
#
# contribs - contribution manager
#
# This test script checks output of contribs scripts when run with '--version'
# parameter.
#
# Copyright (c) 2014, Wiktor Lawski <wiktor.lawski@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

CONTRIBS=$1

read -d '' DRAFT_EXPECTED <<"EOF"
contribs %s

%s
All rights reserved.

https://github.com/wlawski/contribs
EOF

tag_version=`git tag | sort -r`

if [ -z "$tag_version" ]
then
	tag_version=0.99
fi

author=`$CONTRIBS $CONTRIBS |
	grep -v $CONTRIBS |
	grep -v "^$" |
	awk '{
		print "Copyright (c)", $0;
	}'`

EXPECTED=`printf "$DRAFT_EXPECTED" $tag_version "$author"`

RESULT=`$CONTRIBS --version`

./check-result $0 "$EXPECTED" "$RESULT"
exit $?
